### ISSUE TITLE
Arreglar error de ortografía en el readme.md

### ISSUE THREAD

**Issue by ticua07** [janselroa/JanselBot-discord.py-version-1#3]
en la sexta linea del readme.md hay un error de ortografía en enseder que debería ser encender aparte de que faltan unos cuantos tildes
![image](https://user-images.githubusercontent.com/58951699/92047901-afc63c80-ed5c-11ea-82e3-3cbd66c7aebc.png)

PD: puedes hacer un readme con el MS word o documentos de google para que no hayan errores.

**Comment by janselroa** [comment]
arreglar errores ortográficos

**Comment by janselroa** [comment]
arreglar errores ortográficos

**Comment by janselroa** [comment]
arreglar errores ortográficos

**Comment by janselroa** [comment]
arreglar errores ortográficos

**Comment by janselroa** [comment]
arreglar errores ortográficos

**Comment by janselroa** [comment]
arreglar errores ortográficos

**Comment by janselroa** [comment]
arreglar errores ortográficos

**Comment by janselroa** [comment]
arreglar errores ortográficos

**Comment by janselroa** [comment]
arreglar errores ortográficos
